<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\GoogleClassroom;
use Illuminate\Support\Facades\DB;

class GoogleClassroomsController extends Controller
{
    //
    public function init()
    {
       
        $courses = array(
            array('course_id' => '1460','course_code' => 'ACC 101','course_title' => 'Introduction to Fin. Accounting &amp; Reporting I'),
            array('course_id' => '2065','course_code' => 'ACC 201','course_title' => 'Financial Accounting &amp; Reporting I'),
            array('course_id' => '3615','course_code' => 'ACC 203','course_title' => 'Executorship, Bankruptcy Laws and Accounts'),
            array('course_id' => '3616','course_code' => 'ACC 205','course_title' => 'Public Finance'),
            array('course_id' => '2843','course_code' => 'ACC 301','course_title' => 'Intermediate Financial Accounting'),
            array('course_id' => '3684','course_code' => 'ACC 311','course_title' => 'Financial Reporting and ethics'),
            array('course_id' => '2844','course_code' => 'ACC 321','course_title' => 'Cost Accounting'),
            array('course_id' => '2846','course_code' => 'ACC 341','course_title' => 'E-Accounting'),
            array('course_id' => '3617','course_code' => 'ACC 351','course_title' => 'Public Sector Accounting'),
            array('course_id' => '3618','course_code' => 'ACC 361','course_title' => 'Corporate Finance'),
            array('course_id' => '1356','course_code' => 'ACC 401','course_title' => 'Advance Financial Accounting and Reporting I'),
            array('course_id' => '1357','course_code' => 'ACC 411','course_title' => 'Management Accounting II'),
            array('course_id' => '1358','course_code' => 'ACC 431','course_title' => 'Auditing and Investigation II'),
            array('course_id' => '1360','course_code' => 'ACC 441','course_title' => 'Taxation II'),
            array('course_id' => '1359','course_code' => 'ACC 451','course_title' => 'Accounting Seminar'),
            array('course_id' => '1290','course_code' => 'BAF 101','course_title' => 'Introduction to Finance'),
            array('course_id' => '1291','course_code' => 'BAF 201','course_title' => 'The Nigeria Financial Systems'),
            array('course_id' => '1292','course_code' => 'BAF 211','course_title' => 'Banking Methods and Practice'),
            array('course_id' => '3638','course_code' => 'BAF 301','course_title' => 'Banking Methods and Processes'),
            array('course_id' => '3639','course_code' => 'BAF 311','course_title' => 'Practice of Banking'),
            array('course_id' => '3640','course_code' => 'BAF 331','course_title' => 'Monetary Theory and Policy'),
            array('course_id' => '3641','course_code' => 'BAF 341','course_title' => 'Financial Econometrics'),
            array('course_id' => '3642','course_code' => 'BAF 351','course_title' => 'Public Finance'),
            array('course_id' => '3520','course_code' => 'BAF 411','course_title' => 'Financial Management'),
            array('course_id' => '3644','course_code' => 'BAF 421','course_title' => 'Banking Laws and Regulations'),
            array('course_id' => '3646','course_code' => 'BAF 431','course_title' => 'Bank Lending and Loan Administration'),
            array('course_id' => '3519','course_code' => 'BAF 441','course_title' => 'Project Management and Evaluation'),
            array('course_id' => '2005','course_code' => 'BCH 201','course_title' => 'General Biochemistry I'),
            array('course_id' => '2855','course_code' => 'BCH 301','course_title' => 'Introductory Enzymology'),
            array('course_id' => '2856','course_code' => 'BCH 303','course_title' => 'Metabolism of Carbohydrates'),
            array('course_id' => '2858','course_code' => 'BCH 305','course_title' => 'Metabolism of Amino Acids &amp; Proteins'),
            array('course_id' => '2857','course_code' => 'BCH 307','course_title' => 'Metabolism of Lipids'),
            array('course_id' => '2859','course_code' => 'BCH 309','course_title' => 'Metabolism of Nucleic Acids'),
            array('course_id' => '2860','course_code' => 'BCH 311','course_title' => 'Membrane Biochemistry'),
            array('course_id' => '2861','course_code' => 'BCH 313','course_title' => 'Bioenergetics'),
            array('course_id' => '2862','course_code' => 'BCH 315','course_title' => 'Analytical Methods in Biochemistry'),
            array('course_id' => '3509','course_code' => 'BCH 401','course_title' => 'Research Methods &amp; Biochemical Reasoning'),
            array('course_id' => '3500','course_code' => 'BCH 411','course_title' => 'Advanced Enzymology'),
            array('course_id' => '3516','course_code' => 'BCH 413','course_title' => 'Tissue Biochemistry'),
            array('course_id' => '3517','course_code' => 'BCH 415','course_title' => 'Bioinorganic Biochemistry'),
            array('course_id' => '3510','course_code' => 'BCH 421','course_title' => 'Molecular Biology &amp; Genetic Engineering'),
            array('course_id' => '3514','course_code' => 'BCH 431','course_title' => 'Toxicology'),
            array('course_id' => '3513','course_code' => 'BCH 441','course_title' => 'Biosynthesis of Macromolecules'),
            array('course_id' => '3515','course_code' => 'BCH 451','course_title' => 'Forensic Biochemistry'),
            array('course_id' => '3511','course_code' => 'BCH 461','course_title' => 'Metabolic Regulations'),
            array('course_id' => '3512','course_code' => 'BCH 471','course_title' => 'Advanced Biochemical Methods &amp;Instrumentation'),
            array('course_id' => '3600','course_code' => 'BED 431','course_title' => 'Fundamental of Data Processing'),
            array('course_id' => '3499','course_code' => 'BIO 101','course_title' => 'General Biology I'),
            array('course_id' => '1502','course_code' => 'BIO 103','course_title' => 'General Biology Practical 1'),
            array('course_id' => '3497','course_code' => 'BIO 211','course_title' => 'General Genetics I'),
            array('course_id' => '2293','course_code' => 'BIO 214','course_title' => 'Biological Classification and Taxonomy'),
            array('course_id' => '2292','course_code' => 'BIO 231','course_title' => 'General Physiology'),
            array('course_id' => '3498','course_code' => 'BIO 241','course_title' => 'Biological Techniques'),
            array('course_id' => '2956','course_code' => 'BIO 311','course_title' => 'General Genetics II'),
            array('course_id' => '2296','course_code' => 'BIO 311','course_title' => 'General Genetics II'),
            array('course_id' => '2297','course_code' => 'BIO 321','course_title' => 'Evolution'),
            array('course_id' => '2957','course_code' => 'BIO 321','course_title' => 'Evolution'),
            array('course_id' => '2298','course_code' => 'BIO 331','course_title' => 'Field Trip'),
            array('course_id' => '2299','course_code' => 'BIO 341','course_title' => 'Introductory Biotechnology'),
            array('course_id' => '3501','course_code' => 'BIO 411','course_title' => 'Research Methodology'),
            array('course_id' => '3502','course_code' => 'BIO 421','course_title' => 'Seminar'),
            array('course_id' => '3503','course_code' => 'BIO 431','course_title' => 'Principles of Epidemiology and Public Health'),
            array('course_id' => '3504','course_code' => 'BIO 441','course_title' => 'Wild-life Conservation'),
            array('course_id' => '3597','course_code' => 'BIO 451','course_title' => 'Population Ecology'),
            array('course_id' => '2295','course_code' => 'BOT 221','course_title' => 'Seedless Plants'),
            array('course_id' => '3598','course_code' => 'BOT 411','course_title' => 'Soil Science'),
            array('course_id' => '3599','course_code' => 'BOT 421','course_title' => 'Plant Reproduction'),
            array('course_id' => '3596','course_code' => 'BTH 411','course_title' => 'Principles of Biotechnology'),
            array('course_id' => '2837','course_code' => 'BUS 101','course_title' => 'Business Mathematics I'),
            array('course_id' => '1206','course_code' => 'BUS 111','course_title' => 'Introduction to Business I'),
            array('course_id' => '1212','course_code' => 'BUS 201','course_title' => 'Business Statistics'),
            array('course_id' => '3568','course_code' => 'BUS 241','course_title' => 'Elements of Business Administration'),
            array('course_id' => '3079','course_code' => 'BUS 281','course_title' => 'e-Business'),
            array('course_id' => '1218','course_code' => 'BUS 311','course_title' => 'Elements of Management'),
            array('course_id' => '1238','course_code' => 'BUS 321','course_title' => 'Human Resource Management'),
            array('course_id' => '1242','course_code' => 'BUS 341','course_title' => 'Corporate Planning'),
            array('course_id' => '1243','course_code' => 'BUS 351','course_title' => 'Small Business Management'),
            array('course_id' => '1260','course_code' => 'BUS 401','course_title' => 'Business Policy and Strategy I'),
            array('course_id' => '1267','course_code' => 'BUS 411','course_title' => 'International Business'),
            array('course_id' => '1270','course_code' => 'BUS 421','course_title' => 'Public Enterprises Management'),
            array('course_id' => '1273','course_code' => 'BUS 431','course_title' => 'Comparative Management'),
            array('course_id' => '1275','course_code' => 'BUS 441','course_title' => 'Organizational Behaviour'),
            array('course_id' => '1151','course_code' => 'EDM 101','course_title' => 'History of Educational Management in Nigeria'),
            array('course_id' => '3579','course_code' => 'EDM 103','course_title' => 'Introduction to Educational Policies in Nigeria'),
            array('course_id' => '1158','course_code' => 'EDM 201','course_title' => 'Introduction to Educational Management'),
            array('course_id' => '2117','course_code' => 'EDM 205','course_title' => 'Management of Primary and Secondary Education'),
            array('course_id' => '3048','course_code' => 'EDM 301','course_title' => 'Problems and Issues in Planning Nigerian Education'),
            array('course_id' => '3049','course_code' => 'EDM 303','course_title' => 'Leadership in Formal Organization'),
            array('course_id' => '1166','course_code' => 'EDM 305','course_title' => 'The Application of Education Law to School Management'),
            array('course_id' => '3051','course_code' => 'EDM 307','course_title' => 'Educational Supervision in Nigeria'),
            array('course_id' => '3582','course_code' => 'EDM 401','course_title' => 'Demographic Aspect of Educational Management'),
            array('course_id' => '3584','course_code' => 'EDM 403','course_title' => 'Educational Cost and Financial Analysis'),
            array('course_id' => '3585','course_code' => 'EDM 405','course_title' => 'Personnel Management and Evaluation'),
            array('course_id' => '3583','course_code' => 'EDM 411','course_title' => 'Principalship'),
            array('course_id' => '3586','course_code' => 'EDM 425','course_title' => 'Office Management and records Keeping'),
            array('course_id' => '1149','course_code' => 'EDU 111','course_title' => 'Introduction to Teaching Profession'),
            array('course_id' => '1150','course_code' => 'EDU 121','course_title' => 'Foundations of Education I (History and Sociology of Education)'),
            array('course_id' => '2049','course_code' => 'EDU 201','course_title' => 'Educational Psychology II (Human Growth &amp; Development)'),
            array('course_id' => '2048','course_code' => 'EDU 203','course_title' => 'Curriculum Theory and Instruction'),
            array('course_id' => '3053','course_code' => 'EDU 300','course_title' => 'Teaching Practice I/ Internship/ Practicum I'),
            array('course_id' => '2910','course_code' => 'EDU 300','course_title' => 'Teaching Practice I'),
            array('course_id' => '3054','course_code' => 'EDU 301','course_title' => 'Test and Measurements'),
            array('course_id' => '3055','course_code' => 'EDU 303','course_title' => 'Subject Methodology II'),
            array('course_id' => '2911','course_code' => 'EDU 303','course_title' => 'Subject Teaching Methodology II'),
            array('course_id' => '3056','course_code' => 'EDU 305','course_title' => 'Educational Technology'),
            array('course_id' => '2919','course_code' => 'EDU 305','course_title' => 'Educational Technology'),
            array('course_id' => '3636','course_code' => 'EDU 307','course_title' => 'Subject Teaching Methodology II'),
            array('course_id' => '3680','course_code' => 'EDU 319','course_title' => 'Subject Teaching Methodology 11 ( Chemistry)'),
            array('course_id' => '3580','course_code' => 'EDU 400','course_title' => 'Teaching Practice/Practicum II'),
            array('course_id' => '3581','course_code' => 'EDU 401','course_title' => 'Guidance and Counselling'),
            array('course_id' => '3677','course_code' => 'EDU 403','course_title' => 'Subject Teaching Methodology III(English)'),
            array('course_id' => '3593','course_code' => 'EDU 405','course_title' => 'Practice of Educational management'),
            array('course_id' => '3594','course_code' => 'EDU 415','course_title' => 'Subject Teaching Methodology IIII'),
            array('course_id' => '1542','course_code' => 'ENT 101','course_title' => 'Introduction to Enterpreneurship/Intrapreneurship'),
            array('course_id' => '2015','course_code' => 'ENT 201','course_title' => 'Theories of Entrepreneurship'),
            array('course_id' => '3607','course_code' => 'ENT 205','course_title' => 'Introduction to Entrepreneurship/Intrapreneurship'),
            array('course_id' => '3608','course_code' => 'ENT 207','course_title' => 'Sociology of Entrepreneurship'),
            array('course_id' => '2018','course_code' => 'ENT 231','course_title' => 'Basic Financial Literacy'),
            array('course_id' => '2904','course_code' => 'ENT 311','course_title' => 'Psychology of Entrepreneurship'),
            array('course_id' => '3682','course_code' => 'ENT 323','course_title' => 'Feasibiltities Studies &amp; Business Planning'),
            array('course_id' => '2908','course_code' => 'ENT 331','course_title' => 'Natural Resource Management'),
            array('course_id' => '2909','course_code' => 'ENT 351','course_title' => 'Events Management'),
            array('course_id' => '2906','course_code' => 'ENT 381','course_title' => 'Business Opportunity Scouting and Evaluation'),
            array('course_id' => '3610','course_code' => 'ENT 413','course_title' => 'Social Entrepreneurship and Community Development'),
            array('course_id' => '3612','course_code' => 'ENT 415','course_title' => 'Rethinking Traditional Occupation'),
            array('course_id' => '3609','course_code' => 'ENT 421','course_title' => 'E-Business and Entrepreneurship'),
            array('course_id' => '3613','course_code' => 'ENT 427','course_title' => 'Strategic Thinking, Problem Solving and Negotiation Skills'),
            array('course_id' => '3611','course_code' => 'ENT 433','course_title' => 'Technology Entrepreneurship and Intellectual Property Rights'),
            array('course_id' => '3614','course_code' => 'ENT 435','course_title' => 'Entrepreneurship Practicum'),
            array('course_id' => '3637','course_code' => 'FIN 411','course_title' => 'Financial Management'),
            array('course_id' => '1167','course_code' => 'GCE 111','course_title' => 'Introduction to Guidance and Counselling'),
            array('course_id' => '1169','course_code' => 'GCE 113','course_title' => 'Development of Guidance and Counselling'),
            array('course_id' => '1168','course_code' => 'GCE 121','course_title' => 'Principles and Techniques of Guidance and Counselling'),
            array('course_id' => '1170','course_code' => 'GCE 211','course_title' => 'Adolescence Psychology and Guidance and Counselling'),
            array('course_id' => '3131','course_code' => 'GCE 213','course_title' => 'Counselling for Special Needs'),
            array('course_id' => '3132','course_code' => 'GCE 221','course_title' => 'Theories of Counselling'),
            array('course_id' => '3057','course_code' => 'GCE 307','course_title' => 'Practicum in Guidance and Counseling I'),
            array('course_id' => '1175','course_code' => 'GCE 311','course_title' => 'Organization of Guidance and Counselling in Schools'),
            array('course_id' => '1176','course_code' => 'GCE 313','course_title' => 'Occupational Information, Job Analysis and Job Evaluation'),
            array('course_id' => '3059','course_code' => 'GCE 315','course_title' => 'Abnormal Psychology and Career Guidance &amp; Counselling'),
            array('course_id' => '3589','course_code' => 'GCE 413','course_title' => 'Practicum in Guidance and Counselling II'),
            array('course_id' => '3591','course_code' => 'GCE 417','course_title' => 'Introduction to Culture and Psycho-Pathology'),
            array('course_id' => '3522','course_code' => 'GET 201','course_title' => 'Applied Electricity'),
            array('course_id' => '3523','course_code' => 'GET 203','course_title' => 'Engineering Drawing, I'),
            array('course_id' => '3524','course_code' => 'GET 205','course_title' => 'Fundamentals of fluid mechanics'),
            array('course_id' => '3525','course_code' => 'GET 207','course_title' => 'Applied Mechanics'),
            array('course_id' => '3526','course_code' => 'GET 209','course_title' => 'Engineering Mathematics'),
            array('course_id' => '3527','course_code' => 'GET 211','course_title' => 'Computer Programming'),
            array('course_id' => '3528','course_code' => 'GET 213','course_title' => 'General Engineering Laboratory Course'),
            array('course_id' => '1180','course_code' => 'HIR 111','course_title' => 'Introduction to History and Historiography'),
            array('course_id' => '1181','course_code' => 'HIR 113','course_title' => 'Major World Civilization'),
            array('course_id' => '1182','course_code' => 'HIR 115','course_title' => 'Introduction to International Relations'),
            array('course_id' => '2242','course_code' => 'HIR 117','course_title' => 'Introduction to Archeology I'),
            array('course_id' => '1185','course_code' => 'HIR 201','course_title' => 'Themes in Latin America and Caribbean History'),
            array('course_id' => '1184','course_code' => 'HIR 221','course_title' => 'Nigeria to 1900'),
            array('course_id' => '1186','course_code' => 'HIR 223','course_title' => 'Theory and Practice of Diplomacy'),
            array('course_id' => '1187','course_code' => 'HIR 225','course_title' => 'Law and Diplomatic Practices in Pre-colonial Africa'),
            array('course_id' => '1188','course_code' => 'HIR 227','course_title' => 'North Africa since 1800'),
            array('course_id' => '1189','course_code' => 'HIR 229','course_title' => 'East and Central Africa since 1800'),
            array('course_id' => '2131','course_code' => 'HIR 233','course_title' => 'Development of Strategic Thought'),
            array('course_id' => '2130','course_code' => 'HIR 237','course_title' => 'Introduction to Nigerian Government &amp; Politics'),
            array('course_id' => '1195','course_code' => 'HIR 301','course_title' => 'Comparative Political Systems'),
            array('course_id' => '1196','course_code' => 'HIR 311','course_title' => 'Europe since 1789'),
            array('course_id' => '2167','course_code' => 'HIR 313','course_title' => 'Civil-Military Relations'),
            array('course_id' => '1190','course_code' => 'HIR 331','course_title' => 'Defence and Strategic Studies'),
            array('course_id' => '1191','course_code' => 'HIR 333','course_title' => 'International Politics'),
            array('course_id' => '1192','course_code' => 'HIR 335','course_title' => 'Regional Cooperation and Integration in Developing Economies'),
            array('course_id' => '1193','course_code' => 'HIR 337','course_title' => 'History of Commonwealth'),
            array('course_id' => '1194','course_code' => 'HIR 339','course_title' => 'History of Political Thought'),
            array('course_id' => '1198','course_code' => 'HIR 411','course_title' => 'History and Philosophy of Science and Technology'),
            array('course_id' => '1197','course_code' => 'HIR 413','course_title' => 'Seminar in African History'),
            array('course_id' => '1200','course_code' => 'HIR 421','course_title' => 'Modern Revolution (Selected Cases)'),
            array('course_id' => '1199','course_code' => 'HIR 423','course_title' => 'Women in History'),
            array('course_id' => '1202','course_code' => 'HIR 431','course_title' => 'Non-State Actors in World Politics'),
            array('course_id' => '1203','course_code' => 'HIR 433','course_title' => 'International Conflict and Conflict Resolution'),
            array('course_id' => '1204','course_code' => 'HIR 435','course_title' => 'Tradition and Modernity in Africa'),
            array('course_id' => '1201','course_code' => 'HIR 441','course_title' => 'Nation Building in Africa since 1945'),
            array('course_id' => '1179','course_code' => 'HUM 111','course_title' => 'Introduction to Humanities'),
            array('course_id' => '3631','course_code' => 'LAW 305','course_title' => 'Company Law'),
            array('course_id' => '3569','course_code' => 'LAW 311','course_title' => 'Administrative Law'),
            array('course_id' => '3625','course_code' => 'LIS 431','course_title' => 'SIWES'),
            array('course_id' => '3626','course_code' => 'LIS 491','course_title' => 'Research Project 1'),
            array('course_id' => '1553','course_code' => 'MAC 111','course_title' => 'Introduction to Mass Communication'),
            array('course_id' => '2341','course_code' => 'MAC 121','course_title' => 'History of Nigerian Mass Media'),
            array('course_id' => '2340','course_code' => 'MAC 131','course_title' => 'African Communication Systems'),
            array('course_id' => '2168','course_code' => 'MAC 211','course_title' => 'Feature Writing'),
            array('course_id' => '2169','course_code' => 'MAC 221','course_title' => 'Photojournalism'),
            array('course_id' => '2170','course_code' => 'MAC 231','course_title' => 'Integrated Marketing Communication'),
            array('course_id' => '2171','course_code' => 'MAC 241','course_title' => 'News Writing and Reporting'),
            array('course_id' => '2172','course_code' => 'MAC 251','course_title' => 'Theories of Communication'),
            array('course_id' => '2173','course_code' => 'MAC 261','course_title' => 'Speech Communication and Performance'),
            array('course_id' => '2896','course_code' => 'MAC 311','course_title' => 'Creative Advertising, Copy Writing and Media Planning'),
            array('course_id' => '2897','course_code' => 'MAC 321','course_title' => 'Marketing Foundation for Advertising and Public Relations'),
            array('course_id' => '2898','course_code' => 'MAC 331','course_title' => 'Issues in Nigeria Mass Media'),
            array('course_id' => '2899','course_code' => 'MAC 341','course_title' => 'News Paper Management and Production'),
            array('course_id' => '2900','course_code' => 'MAC 351','course_title' => 'Photography Technologies and Processes'),
            array('course_id' => '2901','course_code' => 'MAC 361','course_title' => 'Communication Research'),
            array('course_id' => '3547','course_code' => 'MAC 411','course_title' => 'Issues in Broadcasting'),
            array('course_id' => '3546','course_code' => 'MAC 421','course_title' => 'Film Genre Differentiation'),
            array('course_id' => '3548','course_code' => 'MAC 431','course_title' => 'Station Management and Operations'),
            array('course_id' => '3549','course_code' => 'MAC 441','course_title' => 'Issues in Advertising &amp; Public Relations'),
            array('course_id' => '3550','course_code' => 'MAC 451','course_title' => 'International Public Relations'),
            array('course_id' => '3551','course_code' => 'MAC 461','course_title' => 'Advertising &amp; Public Relations Agencies'),
            array('course_id' => '3552','course_code' => 'MAC 471','course_title' => 'Mass Media Law &amp; Ethics'),
            array('course_id' => '3553','course_code' => 'MAC 481','course_title' => 'Data Analysis in Communication Research'),
            array('course_id' => '1495','course_code' => 'MTH 101','course_title' => 'General Mathematics I'),
            array('course_id' => '2031','course_code' => 'MTH 201','course_title' => 'Mathematical Methods I'),
            array('course_id' => '2126','course_code' => 'MTH 204','course_title' => 'Linear Algebra'),
            array('course_id' => '2072','course_code' => 'MTH 207','course_title' => 'Real Analysis 1'),
            array('course_id' => '1559','course_code' => 'PAD 101','course_title' => 'Introduction to Public Administration'),
            array('course_id' => '2011','course_code' => 'PAD 211','course_title' => 'Nigerian Government and Administration I'),
            array('course_id' => '2010','course_code' => 'PAD 221','course_title' => 'Elements of Public Administration'),
            array('course_id' => '2009','course_code' => 'PAD 231','course_title' => 'Introduction to Local Government'),
            array('course_id' => '2012','course_code' => 'PAD 241','course_title' => 'Office Organization and Management'),
            array('course_id' => '3102','course_code' => 'PAD 301','course_title' => 'Organization and Administrative Theory'),
            array('course_id' => '3105','course_code' => 'PAD 321','course_title' => 'Public Personnel Administration'),
            array('course_id' => '3108','course_code' => 'PAD 331','course_title' => 'Comparative Public Administration'),
            array('course_id' => '3107','course_code' => 'PAD 341','course_title' => 'E-Governance'),
            array('course_id' => '3106','course_code' => 'PAD 351','course_title' => 'Introduction to International Relation'),
            array('course_id' => '3109','course_code' => 'PAD 361','course_title' => 'Traditional Administrative System in Nigeria'),
            array('course_id' => '3111','course_code' => 'PAD 371','course_title' => 'Nigerian Economy'),
            array('course_id' => '3112','course_code' => 'PAD 381','course_title' => 'Social and Welfare Policy in Nigeria'),
            array('course_id' => '3110','course_code' => 'PAD 391','course_title' => 'Human Resource Development and Management'),
            array('course_id' => '3570','course_code' => 'PAD 401','course_title' => 'Public Enterprises Management'),
            array('course_id' => '3571','course_code' => 'PAD 411','course_title' => 'Public Policy Making and Analysis'),
            array('course_id' => '3572','course_code' => 'PAD 421','course_title' => 'Public Financial Administration'),
            array('course_id' => '3573','course_code' => 'PAD 431','course_title' => 'Government and Administration of Urban System'),
            array('course_id' => '3574','course_code' => 'PAD 441','course_title' => 'Project Analysis and Management'),
            array('course_id' => '3575','course_code' => 'PAD 451','course_title' => 'Man Power Planning and Development'),
            array('course_id' => '3576','course_code' => 'PAD 461','course_title' => 'Communication Skills for administration'),
            array('course_id' => '3577','course_code' => 'PAD 471','course_title' => 'Conflict Management'),
            array('course_id' => '3578','course_code' => 'PAD 481','course_title' => 'Gender Studies I'),
            array('course_id' => '2989','course_code' => 'PCS 101','course_title' => 'Introduction to Peace and Conflict Studies 1'),
            array('course_id' => '2990','course_code' => 'PCS 103','course_title' => 'Introduction to Violence and Non-violence'),
            array('course_id' => '2991','course_code' => 'PCS 105','course_title' => 'Introduction to Justice and Human Rights'),
            array('course_id' => '2992','course_code' => 'PCS 107','course_title' => 'Religion, Ethnicity, Gender and Culture'),
            array('course_id' => '3686','course_code' => 'PCS 201','course_title' => 'International Organizations in Peace and Conflict Studies'),
            array('course_id' => '3687','course_code' => 'PCS 203','course_title' => 'Introduction to Peace Processes and Peace-building'),
            array('course_id' => '3688','course_code' => 'PCS 205','course_title' => 'Nationalism, Ethnicity and Conflicts'),
            array('course_id' => '3689','course_code' => 'PCS 211','course_title' => 'Effect and Cost of Conflict'),
            array('course_id' => '3690','course_code' => 'PCS 213','course_title' => 'Media, Peace and Conflict'),
            array('course_id' => '1300','course_code' => 'PHL 101','course_title' => 'Introduction to Philosophy'),
            array('course_id' => '1301','course_code' => 'PHL 103','course_title' => 'Ancient Philosophy I'),
            array('course_id' => '1302','course_code' => 'PHL 105','course_title' => 'Introduction to Logic'),
            array('course_id' => '1562','course_code' => 'PHL 107','course_title' => 'African Philosophy'),
            array('course_id' => '2193','course_code' => 'PHL 201','course_title' => 'Introduction to Epistemology'),
            array('course_id' => '2195','course_code' => 'PHL 203','course_title' => 'Medieval Philosophy'),
            array('course_id' => '2954','course_code' => 'PHL 205','course_title' => 'Arguments and Critical Thinking'),
            array('course_id' => '2194','course_code' => 'PHL 207','course_title' => 'Philosophical Anthropology I'),
            array('course_id' => '2199','course_code' => 'PHL 209','course_title' => 'Philosophy of Social Communication'),
            array('course_id' => '3496','course_code' => 'PHL 211','course_title' => 'Introduction to Metaphysics'),
            array('course_id' => '2955','course_code' => 'PHL 213','course_title' => 'Philosophy of Value'),
            array('course_id' => '2198','course_code' => 'PHL 215','course_title' => 'Philosophy and Globalization'),
            array('course_id' => '1309','course_code' => 'PHL 301','course_title' => 'Early Modern Philosophy'),
            array('course_id' => '2935','course_code' => 'PHL 303','course_title' => 'Advanced Epistemology'),
            array('course_id' => '2936','course_code' => 'PHL 305','course_title' => 'Philosophy of Social Science'),
            array('course_id' => '2937','course_code' => 'PHL 307','course_title' => 'Professional Ethics'),
            array('course_id' => '2938','course_code' => 'PHL 309','course_title' => 'Oriental Philosophy II'),
            array('course_id' => '1314','course_code' => 'PHL 311','course_title' => 'Philosophy of Education'),
            array('course_id' => '2940','course_code' => 'PHL 313','course_title' => 'Gender Philosophy'),
            array('course_id' => '2941','course_code' => 'PHL 315','course_title' => 'Modern African Philosophy'),
            array('course_id' => '2942','course_code' => 'PHL 317','course_title' => 'Study of Texts (Ancient and Medieval)'),
            array('course_id' => '3554','course_code' => 'PHL 401','course_title' => 'Contemporary Philosophy'),
            array('course_id' => '3555','course_code' => 'PHL 403','course_title' => 'Contemporary African Philosophy II'),
            array('course_id' => '3556','course_code' => 'PHL 405','course_title' => 'Further Logic'),
            array('course_id' => '3557','course_code' => 'PHL 407','course_title' => 'Contemporary Issues in Ethics'),
            array('course_id' => '3558','course_code' => 'PHL 409','course_title' => 'Philosophy of Mind I'),
            array('course_id' => '3559','course_code' => 'PHL 411','course_title' => 'Post-Modernist Philosophy'),
            array('course_id' => '3560','course_code' => 'PHL 413','course_title' => 'Philosophy of History'),
            array('course_id' => '3561','course_code' => 'PHL 415','course_title' => 'Seminar I'),
            array('course_id' => '2236','course_code' => 'REL 111','course_title' => 'Introduction to Religious Studies'),
            array('course_id' => '2235','course_code' => 'REL 121','course_title' => 'Sources of Christianity'),
            array('course_id' => '2237','course_code' => 'REL 131','course_title' => 'Survey of African Traditional Religion'),
            array('course_id' => '2238','course_code' => 'REL 141','course_title' => 'Sources of Islam'),
            array('course_id' => '2239','course_code' => 'REL 151','course_title' => 'Introduction to Social Anthropology of Religion'),
            array('course_id' => '2240','course_code' => 'REL 161','course_title' => 'Fundamental Greek'),
            array('course_id' => '2398','course_code' => 'REL 211','course_title' => 'Definition of Religion: A Variety'),
            array('course_id' => '3664','course_code' => 'REL 213','course_title' => 'African Traditional Religion'),
            array('course_id' => '2399','course_code' => 'REL 221','course_title' => 'Introduction to the New Testament'),
            array('course_id' => '2400','course_code' => 'REL 231','course_title' => 'Introduction to the Glorious Qur&#39;an'),
            array('course_id' => '2401','course_code' => 'REL 241','course_title' => 'Introducing Comparative Religion'),
            array('course_id' => '2402','course_code' => 'REL 251','course_title' => 'Introducing Sociology of Religion'),
            array('course_id' => '2403','course_code' => 'REL 261','course_title' => 'Theories of Religion'),
            array('course_id' => '2404','course_code' => 'REL 271','course_title' => 'Biblical Hebrew I'),
            array('course_id' => '2405','course_code' => 'REL 281','course_title' => 'History of Christianity in West Africa'),
            array('course_id' => '2406','course_code' => 'REL 291','course_title' => 'Religion and Human Sexuality'),
            array('course_id' => '3021','course_code' => 'REL 301','course_title' => 'Religion, Conflict and Peace I'),
            array('course_id' => '3676','course_code' => 'REL 301','course_title' => 'Comparative Religions'),
            array('course_id' => '3012','course_code' => 'REL 311','course_title' => 'New Testament Studies II'),
            array('course_id' => '3013','course_code' => 'REL 321','course_title' => 'The Four Orthodox Caliphs in Islam'),
            array('course_id' => '3014','course_code' => 'REL 331','course_title' => 'History of the Reformation'),
            array('course_id' => '3015','course_code' => 'REL 341','course_title' => 'Research Methods'),
            array('course_id' => '3016','course_code' => 'REL 351','course_title' => 'The Spirit World of the African'),
            array('course_id' => '3017','course_code' => 'REL 361','course_title' => 'The Religion of China: Taoism'),
            array('course_id' => '3018','course_code' => 'REL 371','course_title' => 'Old Testament Studies I'),
            array('course_id' => '3019','course_code' => 'REL 381','course_title' => 'Religion and Cultural Tourism'),
            array('course_id' => '3020','course_code' => 'REL 391','course_title' => 'Bio-Medical Ethics'),
            array('course_id' => '3022','course_code' => 'REL 411','course_title' => 'The Writing of the Old and New Testaments'),
            array('course_id' => '3023','course_code' => 'REL 421','course_title' => 'Nigerian Church History'),
            array('course_id' => '3024','course_code' => 'REL 431','course_title' => 'Islamic Theology'),
            array('course_id' => '3025','course_code' => 'REL 441','course_title' => 'Old Testament Studies II'),
            array('course_id' => '3628','course_code' => 'REL 451','course_title' => 'The Supreme Being in African Traditional Religion'),
            array('course_id' => '3629','course_code' => 'REL 461','course_title' => 'Religion, Conflict and Peace II'),
            array('course_id' => '3630','course_code' => 'REL 471','course_title' => 'Seminar on Contemporary Issues in Religion, Culture and Society'),
            array('course_id' => '3077','course_code' => 'SED 315','course_title' => 'Nigerian primary/secondary school science curricula'),
            array('course_id' => '3595','course_code' => 'SED 413','course_title' => 'Science Technology and Society'),
            array('course_id' => '1498','course_code' => 'SSE 111','course_title' => 'Element of Social Studies'),
            array('course_id' => '2050','course_code' => 'SSE 211','course_title' => 'Problems of Ethics and Value Education'),
            array('course_id' => '2051','course_code' => 'SSE 221','course_title' => 'Nigerian Socio- Political Institutions'),
            array('course_id' => '2920','course_code' => 'SSE 313','course_title' => 'Finance and Financial Institution in Nigeria.'),
            array('course_id' => '3588','course_code' => 'SSE 321','course_title' => 'Nationalism and Patriotism in Nigeria'),
            array('course_id' => '3203','course_code' => 'SSE 413','course_title' => 'Social Issues as Emerging Priorities of Social Studies Education'),
            array('course_id' => '3587','course_code' => 'SSE 421','course_title' => 'Social life &amp; Party politics in Nigeria'),
            array('course_id' => '3115','course_code' => 'THY 101','course_title' => 'Introduction to Theology'),
            array('course_id' => '3116','course_code' => 'THY 103','course_title' => 'Introduction to Old Testament'),
            array('course_id' => '3119','course_code' => 'THY 106','course_title' => 'Introduction to Latin I'),
            array('course_id' => '3662','course_code' => 'THY 211','course_title' => 'Introduction to the Pentateuch'),
            array('course_id' => '3151','course_code' => 'THY 223','course_title' => 'Introduction to the Pentateuch'),
            array('course_id' => '3665','course_code' => 'THY 225','course_title' => 'Hebrew Grammar and Syntax I'),
            array('course_id' => '3663','course_code' => 'THY 227','course_title' => 'Patristics'),
            array('course_id' => '3666','course_code' => 'THY 229','course_title' => 'Study of Synoptics'),
            array('course_id' => '3691','course_code' => 'THY 233','course_title' => 'Biblical Hermeneutics'),
            array('course_id' => '3669','course_code' => 'THY 301','course_title' => 'Christology'),
            array('course_id' => '3670','course_code' => 'THY 303','course_title' => 'Doctrine of the Triune God'),
            array('course_id' => '3668','course_code' => 'THY 305','course_title' => 'Pauline Corpus'),
            array('course_id' => '3671','course_code' => 'THY 307','course_title' => 'Pastoral Theology'),
            array('course_id' => '3672','course_code' => 'THY 309','course_title' => 'Theology of Salvation'),
            array('course_id' => '3667','course_code' => 'THY 309','course_title' => 'Inter  Religious Dialogue'),
            array('course_id' => '3673','course_code' => 'THY 311','course_title' => 'Homiletics'),
            array('course_id' => '3674','course_code' => 'THY 313','course_title' => 'Theology of Missions'),
            array('course_id' => '3675','course_code' => 'THY 315','course_title' => 'Research methodology'),
            array('course_id' => '3659','course_code' => 'THY105','course_title' => 'Introduction to New Testament Greek I'),
            array('course_id' => '3660','course_code' => 'THY107','course_title' => 'Introduction to Spirituality'),
            array('course_id' => '3661','course_code' => 'THY109','course_title' => 'Introduction to Latin I'),
            array('course_id' => '3592','course_code' => 'ZOO 211','course_title' => 'Lower Invertebrates'),
            array('course_id' => '1985','course_code' => 'ZOO 221','course_title' => 'Invertebrate Zoology'),
            array('course_id' => '2300','course_code' => 'ZOO 311','course_title' => 'Basic Entomology and Pest Control'),
            array('course_id' => '2301','course_code' => 'ZOO 321','course_title' => 'Cell and Molecular Biology'),
            array('course_id' => '2302','course_code' => 'ZOO 331','course_title' => 'Protozoology'),
            array('course_id' => '2304','course_code' => 'ZOO 351','course_title' => 'Histology'),
            array('course_id' => '3505','course_code' => 'ZOO 411','course_title' => 'Comparative Vertebrate Anatomy/Zoology'),
            array('course_id' => '3506','course_code' => 'ZOO 421','course_title' => 'Histology and Embryology'),
            array('course_id' => '3507','course_code' => 'ZOO 431','course_title' => 'Animal Pathology')
        );
       
        $n = 1;
        foreach ($courses as $course)
        {
            echo $n." - ".$course['course_code']." - ".$course['course_title']."<br />";
            $n++;
        }
dd();
DB::beginTransaction(); //Start transaction!

foreach ($courses as $course)
{
    $classroom = new GoogleClassroom();
     
$classroom->course_id = $course['course_id'];
$classroom->course_code = $course['course_code'];
$classroom->course_title = $course['course_title'];
$classroom->status = 0;
try {
    //saving logic here
    $classroom->save();
} // end try

catch(\Exception $e)
{
    //failed logic here
    DB::rollback();
    dd($e);
    dd("Error creating ".$classroom->course_code);
}
   
} // end foreach


DB::commit();
dd("Database creation completed.");
    }

} // end Class
